/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pigcomput.main;

import com.pigcomput.tj.Em_BLASSO;
import com.pigcomput.tj.gBLUP;
import com.pigcomput.tj.Polygenic;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRootPane;
import javax.swing.UIManager;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author Asus
 */
public class MiniIGS extends javax.swing.JFrame {

    private gBLUP gblup;
    private Em_BLASSO em_lasso;
    private Polygenic polygenic;

    private Desk2 m;

    /**
     * Creates new form Main1
     */
    public MiniIGS() {
        initComponents();
        //居中
        setLocationRelativeTo(null);
        //窗口风格
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        changeTitle("Times New Roman", Font.PLAIN, 14);
        set();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iGS: Integrated Genomic Selection software");
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(755, 620));
        setResizable(false);

        jPanel1.setMaximumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 620));

        jLabel9.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(198, 250, 99));
        jLabel9.setEnabled(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(198, 250, 99));
        jLabel10.setEnabled(false);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(198, 250, 99));
        jLabel8.setEnabled(false);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/bg.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(198, 250, 99));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(198, 250, 99));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(198, 250, 99));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("方正姚体", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(198, 250, 99));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(538, 538, 538)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(468, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(518, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(280, 280, 280)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabel12)
                    .addContainerGap(491, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(516, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(50, 50, 50)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(291, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(275, 275, 275)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(411, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(253, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(185, 185, 185)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(354, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(65, 65, 65)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(356, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel14)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );

        jPanel1.add(jLabel3, 3);
        jPanel1.add(jLabel8, 2);
        jPanel1.add(jLabel9, 2);
        jPanel1.add(jLabel10, 2);
        jPanel1.add(jLabel11, 2);
        jPanel1.add(jLabel12, 1);
        jPanel1.add(jLabel13, 1);
        jPanel1.add(jLabel14, 1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
//        showMethod(gblup);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
//        showMethod(em_lasso);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
//        showMethod(polygenic);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased

        showMethod(em_lasso);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased

        showMethod(polygenic);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased

        showMethod(gblup);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseReleased

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/32.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/23.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/12.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pigcomput/image/30.png")));
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    private void showMethod(Object obj) {
//        m = new Desk2(new java.awt.Frame(), true);
        Class clazz = obj.getClass();
        try {
            Method setDate = clazz.getMethod("setData");
        } catch (Exception ex) {
//            Logger.getLogger(Main1.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("gBLUP")) {
            m.setTitle("gBLUP: Genome Best Linear Unbiased Prediction");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("Demo")) {
            m.setTitle("Best Method for GS");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("BayesA")) {
            m.setTitle("Bayes A");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("BayeB")) {
            m.setTitle("Bayes B");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("BayesC")) {
            m.setTitle("Bayes C");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("BayesCpi")) {
            m.setTitle("Bayes Cpi");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("BayesLASSO")) {
            m.setTitle("Bayes LASSO");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("Em_BLASSO")) {
            m.setTitle("Em-LASSO");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("RRBLUP")) {
            m.setTitle("rr BLUP");
        } else if (clazz.getName().substring(clazz.getName().lastIndexOf(".") + 1).equals("Polygenic")) {
            m.setTitle("Polygenic");
        }

        m.setSize(((javax.swing.JInternalFrame) obj).getSize().width + 55, ((javax.swing.JInternalFrame) obj).getSize().height + 78);
        m.jPanel1.add((javax.swing.JInternalFrame) obj);

        ((javax.swing.JInternalFrame) obj).setVisible(true);
        m.setLocationRelativeTo(this);

        m.setVisible(true);
    }

    public void set() {
//        "<html>"+"<p>第一行</p>"+
//                "<p>第二行</p>"+
//                "</html>"
        jLabel14.setToolTipText("<html>"+"<p>                            gBLUP: Genomic Best Linear Unbiased Prediction.</p>"
  +"<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Genetic variance was estimated using EMMA </p>"
   +"<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;algorithm.</p>"
                +"</html>");
        jLabel12.setToolTipText("<html>"+"<p>                            EM-LASSO: An expectation-maximization algorithm for</p>"
   +"<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
                                                                      +"&nbsp;&nbsp;the Lasso estimation of marker effects.</p>"
   + "</html>");
        jLabel13.setToolTipText("<html>"+"<p>                      Polygenic model: Polygenic variance components were</p>"
   + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
                                 + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;estimated using mixed model.</p>"+
                "</html>");
        jLabel11.setToolTipText("<html>"+"<p>iGS is an integrated Genomic Selection software, It</p>"
                                       + "<p>implemented three models: gBLUP, EM-LASSO </p>"
                + "<p>and a multiple random effects model.</p>");
                
        m = new Desk2(new java.awt.Frame(), true);

        gblup = new gBLUP(m);
        em_lasso = new Em_BLASSO(m);
        polygenic = new Polygenic(m);
    }

    private void changeTitle(String font1, int type, int size) {
        dispose();
        setUndecorated(true);
        Font font;
        font = new Font(font1, type, size);

        for (Component c : getLayeredPane().getComponents()) {
            if (c.getClass().getName().contains("org.jb2011.lnf.beautyeye.ch1_titlepane.BETitlePane")) {
                c.setFont(font);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniIGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniIGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniIGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniIGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.put("RootPane.setupButtonVisible", false);
            BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.FrameBorderStyle.translucencyAppleLike;
            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } catch (Exception e) {

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // 755,620    701,547
                long time1 = System.currentTimeMillis();
                new MiniIGS().setVisible(true);

                long time2 = System.currentTimeMillis();
//                System.out.println("login2App"+(time2-time1));

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
