/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pigcomput.tj;

import com.Em.operate.FileCV;
import com.pigcomput.main.Desk2;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import zb.archer.Demo.domain.CluButton;
import zb.archer.Demo.domain.CluFinButton;
import zb.archer.Demo.operate.FileTraits;
import zb.archer.Demo.operate.OperateNumG;
import zb.archer.Demo.operate.OperateNumGM;
import zb.archer.Demo.operate.Write;

/**
 * FileDialog loadDiaA 育种分析文件 FileDialog loadDiaPhe 表性信息文件 FileDialog writeDia
 * 导出BLUP结果文件 double[][] pedigree 育种分析值 String[] name 育种分析个体名 String[] ColName
 * 表型列名 String[][] resultstr BLUP结果 SelectBxsz sb 表型选择dialog String[] tableHead
 * 表 Object[][] tableModel
 *
 * @author Asus
 */
public class Em_BLASSO extends javax.swing.JInternalFrame {

    //文件
    private FileDialog loadDiaCV;
    private FileDialog loadDiaGD;
    private FileDialog loadDiaY;
    private FileDialog loadDiaGM;
    //写文件
    private FileDialog writeDia;
    //个体值
//    private double[][] pedigree;
    //个体名
//    private String[] name;
    private String[] ColName;
    private String[][] resultstr;
//    private double[][] forecas;
    private SelectBxsz sb;
    private String[] tableHead = {"Colnumn", "Traits"};
    private Object[][] tableModel;
    private double[][] forecas;

    private boolean standard_id = false;

    private Desk2 d;
    private CluButton cb1;
    private final ButtonGroup b2;

    /**
     * Creates new form Blup
     */
    public Em_BLASSO(Desk2 d) {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setData();
        this.d = d;

        b2 = new ButtonGroup();
        b2.add(jRadioButton5);
        b2.add(jRadioButton6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(233, 242, 252));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("BayesA计算");
        setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(133, 34));
        setPreferredSize(new java.awt.Dimension(650, 545));

        jPanel1.setBackground(new java.awt.Color(233, 242, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(994, 50));

        jButton2.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Run");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Export .txt");
        jButton4.setEnabled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Export .csv");
        jButton3.setEnabled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 102));
        jButton6.setText("Select Traits");
        jButton6.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Colnumn", "Traits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("myGD File");
        jButton1.setPreferredSize(new java.awt.Dimension(147, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText(" ");

        jButton5.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("myY  File");
        jButton5.setPreferredSize(new java.awt.Dimension(147, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText(" ");

        jButton9.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 102));
        jButton9.setText("myGM File");
        jButton9.setPreferredSize(new java.awt.Dimension(147, 32));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel9.setText(" ");

        jButton10.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 102));
        jButton10.setText("myCV File");
        jButton10.setPreferredSize(new java.awt.Dimension(147, 32));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel10.setText(" ");

        jButton7.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 102));
        jButton7.setText("Reset");
        jButton7.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(0, 0, 102));
        jButton24.setText("Return");
        jButton24.setPreferredSize(new java.awt.Dimension(110, 32));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(233, 242, 252));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Title of myGD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        jRadioButton5.setBackground(new java.awt.Color(233, 242, 252));
        jRadioButton5.setText("No");

        jRadioButton6.setBackground(new java.awt.Color(233, 242, 252));
        jRadioButton6.setText("Yes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton6)
                .addGap(60, 60, 60)
                .addComponent(jRadioButton5)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //开始计算
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //判断是否导入两个文件
        if ((loadDiaGD == null || loadDiaGD.getDirectory() == null)
                || (loadDiaY == null || loadDiaY.getDirectory() == null)) {
            CluFinButton.CluFinButton("Please import the files first!", JOptionPane.ERROR_MESSAGE, "Error");
            return;
        }
        FileTraits fb = new FileTraits(loadDiaY.getDirectory() + loadDiaY.getFile());
        if (tableModel.length == ColName.length) {
            boolean[] bool1 = new boolean[fb.getColName().length - 1];
            for (int i = 0; i < bool1.length; i++) {
                bool1[i] = true;
            }
            if (closeList(bool1, fb, 2) == 1) {
                return;
            }
        }

        Thread t3 = new Thread(new Runnable() {
            public void run() {
                try {
                    boolean tip = false;
                    if (jRadioButton6.isSelected()) {
                        tip = true;
                    }

                    //表型数组
                    ArrayList<Integer> indexlist = new ArrayList<Integer>();
                    for (int i = 0; i < sb.bool1.length; i++) {
                        if (sb.bool1[i]) {
                            indexlist.add(i);
                        }
                    }
                    Object[] temp1 = indexlist.toArray();
                    int[] index1 = new int[temp1.length];
                    for (int i = 0; i < temp1.length; i++) {
                        index1[i] = (int) temp1[i];
                    }

                    FileCV myCV = null;
                    FileTraits myY = null;
                    OperateNumG myGD = null;
                    OperateNumGM myGM = null;
                    if (loadDiaCV != null && loadDiaCV.getDirectory() != null) {
                        myCV = new FileCV(loadDiaCV.getDirectory() + loadDiaCV.getFile());
                    } else {
                        myCV = new FileCV();
                    }
                    myY = new FileTraits(loadDiaY.getDirectory() + loadDiaY.getFile());
                    myGD = new OperateNumG(loadDiaGD.getDirectory() + loadDiaGD.getFile(), tip);
                    if (loadDiaGM != null && loadDiaGM.getDirectory() != null) {
                        myGM = new OperateNumGM(loadDiaGM.getDirectory() + loadDiaGM.getFile(), true);
                    } else {
                        myGM = OperateNumGM.randomGM(myGD.getNum()[0].length);
                    }

                    Map<String, Object> map = com.Em.main.Em_lasso.runEn_lasso(myCV.toDoubleArray(), myGD.getNum(), myY.toDoubleArray(), myGM.getNum(), myGM.getName(), index1, myY.getPheName(), myY.getColName(), myY.getPhe3(), myGD.getName());

                    resultstr = (String[][]) map.get("result");
                    forecas = (double[][]) map.get("forecas");
                } catch (Exception e) {
                    cb1.shutdown();
                    CluFinButton.CluFinButton("Sorry! The files import error or the parameters set error. Please load new files or reset! ", JOptionPane.ERROR_MESSAGE, "Error");
                    return;
                }
                cb1.shutdown();
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                CluFinButton.CluFinButton("Finished successfully!", JOptionPane.INFORMATION_MESSAGE, "Hint");
            }
        });
        cb1 = new CluButton(t3);
        cb1.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    //导出txt文件
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        writeDia = new FileDialog(new Frame(), "SAVE", FileDialog.SAVE);
        writeDia.setVisible(true);// TODO add your handling code here:
        if (writeDia.getDirectory() != null && writeDia.getFile() != null) {
            Write.write(writeDia.getDirectory() + writeDia.getFile(), resultstr, forecas, 2);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    //导出csv文件
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        writeDia = new FileDialog(new Frame(), "SAVE", FileDialog.SAVE);
        writeDia.setVisible(true);// TODO add your handling code here:
        if (writeDia.getDirectory() != null && writeDia.getFile() != null) {
            Write.write(writeDia.getDirectory() + writeDia.getFile(), resultstr, forecas, 1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    //选择表型
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (loadDiaY == null || loadDiaY.getDirectory() == null) {
            CluFinButton.CluFinButton("Please import the files first!", JOptionPane.ERROR_MESSAGE, "Error");
            return;
        }

        FileTraits fb = new FileTraits(loadDiaY.getDirectory() + loadDiaY.getFile());
        ColName = new String[fb.getColName().length - 1];
        System.arraycopy(fb.getColName(), 1, ColName, 0, fb.getColName().length - 1);
        sb = new SelectBxsz(ColName, null, true);
        sb.setLocationRelativeTo(this);
        sb.setVisible(true);
        if (sb.stat == 0) {
            closeList(sb.bool1, fb, 2);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        loadDiaGD = new FileDialog(new Frame(), "LOAD", FileDialog.LOAD);
        loadDiaGD.setVisible(true);
        String directory = loadDiaGD.getDirectory();
        String file = loadDiaGD.getFile();
        if (directory != null && file != null) {
            if ((directory + file).length() < 40) {
                jLabel5.setText("" + directory + file);
                jLabel5.setToolTipText(null);
            } else {
                jLabel5.setText(directory.substring(0, directory.indexOf(File.separator)) + File.separator + "..." + File.separator + file);
                jLabel5.setToolTipText(directory + file);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        loadDiaY = new FileDialog(new Frame(), "LOAD", FileDialog.LOAD);
        loadDiaY.setVisible(true);// TODO add your handling code here:
        String directory = loadDiaY.getDirectory();
        String file = loadDiaY.getFile();
        if (directory != null && file != null) {
            if ((directory + file).length() < 40) {
                jLabel6.setText("" + directory + file);
                jLabel6.setToolTipText(null);
            } else {
                jLabel6.setText(directory.substring(0, directory.indexOf(File.separator)) + File.separator + "..." + File.separator + file);
                jLabel6.setToolTipText(directory + file);
            }
        } else {
            return;
        }
        //初始默认选择全部表型
        FileTraits fb = new FileTraits(loadDiaY.getDirectory() + loadDiaY.getFile());
        boolean[] bool1 = new boolean[fb.getColName().length - 1];
        for (int i = 0; i < bool1.length; i++) {
            bool1[i] = true;
        }
        ColName = new String[fb.getColName().length - 1];
        System.arraycopy(fb.getColName(), 1, ColName, 0, fb.getColName().length - 1);
        sb = new SelectBxsz(ColName, null, true);
        sb.setAllBool1True();
        closeList(bool1, fb, 1);

        // TODO add your handling code here:        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        loadDiaGM = new FileDialog(new Frame(), "LOAD", FileDialog.LOAD);
        loadDiaGM.setVisible(true);
        String directory = loadDiaGM.getDirectory();
        String file = loadDiaGM.getFile();
        if (directory != null && file != null) {
            if ((directory + file).length() < 40) {
                jLabel9.setText("" + directory + file);
                jLabel9.setToolTipText(null);
            } else {
                jLabel9.setText(directory.substring(0, directory.indexOf(File.separator)) + File.separator + "..." + File.separator + file);
                jLabel9.setToolTipText(directory + file);
            }
        }
        // TODO add your handling code here:        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        loadDiaCV = new FileDialog(new Frame(), "LOAD", FileDialog.LOAD);
        loadDiaCV.setVisible(true);
        String directory = loadDiaCV.getDirectory();
        String file = loadDiaCV.getFile();
        if (directory != null && file != null) {
            if ((directory + file).length() < 40) {
                jLabel10.setText("" + directory + file);
                jLabel10.setToolTipText(null);
            } else {
                jLabel10.setText(directory.substring(0, directory.indexOf(File.separator)) + File.separator + "..." + File.separator + file);
                jLabel10.setToolTipText(directory + file);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        setData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

        setData();
        d.jPanel1.removeAll();
        d.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    //更新表型表格
    private int closeList(boolean[] bool1, FileTraits fb, int stat) {

        ArrayList<Integer> index = new ArrayList<Integer>();
        int ide = -1;
        for (int i = 0; i < bool1.length; i++) {
            if (bool1[i]) {
                index.add(i + 1);
            }
        }
        if (stat == 1) {
            tableModel = new Object[index.size()][2];
            for (int i = 0; i < tableModel.length; i++) {
                tableModel[i][0] = i + 1;
                tableModel[i][1] = ColName[i];
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(tableModel, tableHead));
            return 0;
        }

        try {
            String[][] temp = fb.getPhe1();
            double t1;
            for (int k = 0; k < index.size(); k++) {
                ide = k;
                if (!temp[0][index.get(k) - 1].equals("NA")) {
                    t1 = Double.parseDouble(temp[0][index.get(k) - 1]);
                }
            }
        } catch (Exception e) {
            CluFinButton.CluFinButton("Values of " + ColName[ide] + " isn't numeric.", JOptionPane.ERROR_MESSAGE, "Error");
            return 1;
        }

        tableModel = new Object[index.size()][2];
        for (int i = 0; i < tableModel.length; i++) {
            tableModel[i][0] = index.get(i);
            tableModel[i][1] = ColName[index.get(i) - 1];
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(tableModel, tableHead));
        return 0;
    }

    //初始化
    public void setData() {
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jRadioButton5.setSelected(true);
        loadDiaCV = null;
        loadDiaGD = null;
        loadDiaY = null;
        loadDiaGM = null;
        writeDia = null;

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[0][2], tableHead)
        );
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        //    jDesktopPane2.removeAll();
        //    jDesktopPane2.add(jLabel6);
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public void setTableModel(Object[][] tableModel) {
        this.tableModel = tableModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
