/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pigcomput.tj;

import com.pigcomput.exception.ArithmeticExceptionImp;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import zb.archer.Demo.domain.CluFinButton;

/**
 *
 * @author Asus
 */
public class SelectBxsz extends javax.swing.JDialog {

    public boolean[] bool1;
    public JPanel contentPane;
    private JPanel panel;
    JCheckBox[] boxs;
    int col;
    int row;
    int stat = 1;
    /*
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
     */
    public StringBuilder title = new StringBuilder("");
    //private String[] title1 = {"\t品种", "\t品系", "\t当前状态", "\t性别", "\t出生重量", "\t出生胎次", "\t断奶重量", "\t采精次数", "\t当前胎次", "\t产仔总数"};

    /**
     * Creates new form SelectGtxx1
     */
    public SelectBxsz(String[] labels, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        col = labels.length / 10 + (labels.length % 10 > 0 ? 1 : 0);
        // 文件 分隔符 不为 \t 时， 这里报错，
        try {
            row = labels.length / (col) + (labels.length % (col) > 0 ? 1 : 0);
            initComponents();
            //setPreferredSize( new java.awt.Dimension(204, (labels.length/2+(labels.length%2>0?1:0))*34+38) );
            //setSize(245, (labels.length/2+(labels.length%2>0?1:0))*45+38  );
            //setSize(( labels.length/10+(labels.length%2>0?1:0) )*245, (11)*45+38  );

            //setSize(contentPane.getHeight(),contentPane.getWidth());
            bool1 = new boolean[labels.length];
            changeTitle("Times New Roman", Font.PLAIN, 12);
            CheckBoxArray(labels);
        } catch (ArithmeticException e) {
            CluFinButton.CluFinButton("Error!", JOptionPane.INFORMATION_MESSAGE, "Hint");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Traits");
        setSize(col*204/2, row*34+38 );

        jPanel1.setPreferredSize(new java.awt.Dimension(204, 28));

        jButton2.setText("All");
        jButton2.setMaximumSize(new java.awt.Dimension(57, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(57, 28));
        jButton2.setPreferredSize(new java.awt.Dimension(57, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.setMaximumSize(new java.awt.Dimension(57, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(57, 28));
        jButton1.setPreferredSize(new java.awt.Dimension(57, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 147, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        for (int i = 0; i < boxs.length; i++) {
            if (boxs[i].isSelected()) {
                bool1[i] = true;
            }
        }
        stat = 0;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        for (int i = 0; i < boxs.length; i++) {
            boxs[i].setSelected(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Launch the application.
     */
    /*
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Throwable e) {
            e.printStackTrace();
        }
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    SelectBxsz sb  = new SelectBxsz(new String[]{"时间","时间","时间","时间","时间","时间","时间","时间","时间","时间"
                        ,"时间","时间","时间","时间","时间","时间","时间","时间","时间"
                        ,"时间","时间","时间","时间","时间","时间","时间","时间","时间"
                        ,"时间"}
                            ,null,true
                    );
                    sb.setVisible(true);
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
     */
    /**
     * Create the frame.
     */
    private void CheckBoxArray(String[] labels) {
        //setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        contentPane = new JPanel();
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        contentPane.setLayout(new BorderLayout(0, 0));
        setContentPane(contentPane);
        contentPane.add(getPanel(labels), BorderLayout.CENTER);
        contentPane.add(jPanel1, BorderLayout.SOUTH);
        //contentPane.add(getButton(), BorderLayout.SOUTH);
        //contentPane.add(jButton2, BorderLayout.SOUTH);

    }

    private JPanel getPanel(String[] labels) {
        if (panel == null) {
            panel = new JPanel();// 创建面板对象
            if (labels.length <= 10) {
                panel.setLayout(new GridLayout(labels.length, 0));// 设置网格布局管理器
            } else {
                panel.setLayout(new GridLayout(row, 0));
            }

            boxs = new JCheckBox[labels.length];// 创建控件数组
            for (int i = 0; i < boxs.length; i++) {// 遍历控件数组
                boxs[i] = new JCheckBox(labels[i]);// 初始化数组中的复选框组件
                panel.add(boxs[i]);// 把数组元素（即每个复选框）添加到面板中
            }
        }
        return panel;
    }

    private JButton getButton() {

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        return jButton1;
    }

    public void setAllBool1True() {
        for (int i = 0; i < bool1.length; i++) {
            bool1[i] = true;
        }
    }
    
    private void changeTitle(String font1, int type, int size) {
        dispose();
        setUndecorated(true);
        Font font ;
        font = new Font(font1, type, size);
        
        for(Component c :getLayeredPane().getComponents()){
//            System.out.println(c.getClass().getName());
            if(c.getClass().getName().contains("org.jb2011.lnf.beautyeye.ch1_titlepane.BETitlePane")){
                c.setFont(font);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
